### ISSUE TITLE
ViFi For germline

### ISSUE THREAD

**Issue by Jordi-V** [namphuon/ViFi#16]
Hi everyone,

I'have a question about ViFi, I want to detect a germline virus integrations in my samples, I want to know if its possible use ViFi for this prupose... Even more, If I have different files for fastq_1 and fastq_2 I'have to merge all of them in one for _1 and other for _2??

Thanks for your help

Jordi

**Comment by Jordi-V** [comment]
Sorry, final question is where I can found the ref genome + viruses used in your program...

Thanks

Jordi

**Comment by Jordi-V** [comment]
Sorry, I have WGS DNA samples, so I can use the VIFI? I need mRNA??

Thanks

**Comment by namphuon** [comment]
Hi Jordi,

Very sorry for long delay.  I've completely overhauled all of ViFi in order to fix the many software version issues.  Included with this overhaul is a new pipeline for building the reference dataset, but briefly, if you follow the new instructions and run the setup_linux_mac.sh script, it will build the hg19+hpv reference data for you.

ViFi takes both WGS and RNA-seq data.
